version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
  backend:
    build: ./server/
    ports:
    - "6200:6200"
    volumes:
    - ./server:/usr/src/app
    depends_on:
    - mariadb
  frontend:
    build: ./front/
    ports:
    - "3000:3000"
    - "35729:35729"
    volumes:
    - ./front:/usr/src/app
    depends_on:
    - backend
